//
// Created by Tiago on 23/10/2016.
//

#ifndef MOBILERAYTRACER_CONSTANTS_HPP
#define MOBILERAYTRACER_CONSTANTS_HPP

#define MAX_LENGTH 1.0e10f
#define MIN_LENGTH 1.0e-6f

#endif //MOBILERAYTRACER_CONSTANTS_HPP